### ISSUE TITLE
is this working configuration

### ISSUE THREAD

**Issue by JZZQuant** [morfikov/android_device_tp-link_tp701a#1]
I have tried building a vanilla aosp oreo using your configuration, i ran into boot loops, i figured you have mentioned  in this forum that you also rand into the same issue https://forum.xda-developers.com/showthread.php?t=1943625&page=281.

Were you eventually able to get it working after modifying the cortex to generic? i am still struggling with bootloops. also any ideas on the next steps for building full fledge rom aosp or omni?

**Comment by morfikov** [comment]
If you want to build the whole ROM, you need to work on many things. This configuration is only for building the TWRP recovery, which is a way easier task.

**Comment by JZZQuant** [comment]
so you were able to get the recovery part working with this device tree. Did you use omni code base? 
iam assuming these are the steps you followed in a nutshell
get omni repo init and sync
add the device tree to repo folder
lunch and make.
are there any other tweaks you had to follow than the standard instructions.
for working on rom my assumption is getting the right vendor tree is important anything else particularly important for this particular device
can you write a blog or github wiki of your experience so far it would be greatly helpful.

**Comment by morfikov** [comment]
You have everything in the description.
